spring:
  application:
    name: arkhive

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect


management:
  endpoint:
    health:
      show-details: always
    prometheus:
      access: read_only
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

arkhive:
  auth:
    expiration: ${TOKEN_EXPIRATION}
    secret: ${TOKEN_SECRET}
    refresh-token-secret: ${REFRESH_TOKEN_SECRET}
    refresh-token-expiration: ${REFRESH_TOKEN_EXPIRATION}


  mailtrap:
    token: ${MAILTRAP_API_TOKEN}
    mail-sender: ${MAIL_SENDER}

  password-reset:
    secret: ${PASSWORD_RESET_TOKEN_SECRET}
    expiration: ${PASSWORD_RESET_TOKEN_EXPIRATION}
    reset-endpoint: http://localhost:8080/api/v1/user/password/reset?token=

  s3:
    uri: ${S3_URI}
    access-key: ${CREDENTIAL_ACCESS_KEY}
    secret-key: ${CREDENTIAL_SECRET_ACCESS_KEY}
    bucket: ${BUCKET_NAME}

  musicbrainz:
    token: ${MUSICBRAINZ_TOKEN}